#!/bin/sh

#SBATCH -J rpmd
#SBATCH -t 400:00:00
#SBATCH -n 1
#SBATCH -N 1
#SBATCH -p astra
#SBATCH -o %x.o%j
#SBATCH -e %x.e%j
#SBATCH -x c0055
#SBATCH --mail-type=ALL

# Enter the working directory
cd ${SLURM_SUBMIT_DIR}
echo "starting $SLURM_JOB_ID at `date` on `hostname`"
echo "$USER"
echo $SLURM_SUBMIT_DIR
NUMNODES=1
SIMDIR='/home/fs01/netID/mavaric_v2.1/'
SIM='mvrpmd'

# Make a temp directory
/usr/bin/mkdir -p /tmp/$USER/$SLURM_JOB_ID

# Copy files to the temp directory
cp $SLURM_SUBMIT_DIR/bin/$SIM     /tmp/$USER/$SLURM_JOB_ID/.

mpirun -np $NUMNODES /home/fs01/netID/mavaric_v2.1/bin/$SIM $SIMDIR $SIM

# Copy output files back from the temp directory to working directory
rsync -r /tmp/$USER/$SLURM_JOB_ID/ $SLURM_SUBMIT_DIR/

rm -rf /tmp/$USER/$SLURM_JOB_ID/
exit 0
